### ISSUE TITLE
Details for xhr requests

### ISSUE THREAD

**Issue by shinobi64** [bahmutov/cypress-failed-log#120]
The logging of the commands upon error in the cypress test works fine (it already saved me a couple of hours analyzing issues from test runs on our CI). However the details for the assertion is not always the only information for being able to track down an issue. In some cases it's required to see which requests have been made before/ afterwards.

In the Cypress UI for each XHR request the URL and the status is displayed - but in the logged files on error only the entry xhr exists without further details. Is there any possibility to access the the URL and the status for the xhr command to get this information into the log as well?

**Comment by folmert** [comment]
+1 as this:

> visit /index-form.html
> xhr 
> xhr 
> contains h2, Personal details

is not very helpful

**Comment by bahmutov** [comment]
Agree, I would welcome a pull request with more details for an XHR

**Comment by shinobi64** [comment]
@bahmutov pull request #134 created for adding some more details for the xhr command log
