### ISSUE TITLE
afterEach failure: `this` is undefined

### ISSUE THREAD

**Issue by mccataldo** [bahmutov/cypress-failed-log#151]
Once installing this plugin, my `afterEach` broke because I'm referencing `this.currentTest`:
```
TypeError: Cannot read property 'currentTest' of undefined
```
 In `src/index.js` why not perform `call` on `fn` like with `onFailed`?
```
  _afterEach(name, function () {
    onFailed.call(this)
    fn.call(this)
  })
``` 
This fixes it for me. Should I submit a PR?

**Comment by bahmutov** [comment]
A pull request would be greatly appreciated and an accompanying test if possible

**Comment by mccataldo** [comment]
@bahmutov sure, but now I'm dealing with another issue: #152

**Comment by bahmutov** [comment]
Oh my, things are just not working today ;)
