### ISSUE TITLE
Why does cypress-failed-log need to take screenshots?

### ISSUE THREAD

**Issue by c32hedge** [bahmutov/cypress-failed-log#204]
Since Cypress already takes screenshots on failed tests, the screenshot taken by `cypress-failed-log` seems redundant. In addition, I've seen some issues where the `cypress-failed-log` screenshot fails in certain cases, whereas the default screenshot doesn't. Is this an obsolete feature at this point?

**Comment by bahmutov** [comment]
Probably yes
