### ISSUE TITLE
when using cypress-cucumber-preprocessor , skipped tests are logged as failed

### ISSUE THREAD

**Issue by jankowskimarcin** [bahmutov/cypress-failed-log#253]
{
  "specName": "*.feature",
  "title": "",
  "suiteName": "",
  "testName": "",
  "testError": "sync skip; aborting execution",
  "testCommands": [
    "then function(){}"
  ]
}

**Comment by bahmutov** [comment]
Sorry, not using cucumber, cannot help with this
