### ISSUE TITLE
The 'task' event has not been registered in the plugins file

### ISSUE THREAD

**Issue by tnguyen14** [bahmutov/cypress-failed-log#262]
I have been using this plugin successfully for a while.

```js
// cypress/plugins/index.js
modules.exports = (on, config) => {
  on('task', {
    failed: require('cypres-failed-log/src/failed')()
  });
};
```
```js
// cypress/support/index.js
import 'cypress-failed-log';
```

However, recently I switched to esmodule by adding this in `package.json`

```json
  "type": "module"
```

I renamed `cypress/plugins/index.js` to `cypress/plugins/index.cjs`. Cypress run fails, but upon failure, I got the following error message

```
      CypressError: `cy.task('failed')` failed with the following error:

The 'task' event has not been registered in the plugins file. You must register it before using cy.task()
```

Is there anything special I need to do fix this?

**Comment by KleisKlasKluss** [comment]
I started getting this error too after bumping Cypress version from 6.9.1 to any version that requires node 12+ (i.e. version 7.x and upwards).
Any idea why @bahmutov ?

**Comment by bahmutov** [comment]
This is Cypress problem, see the solution in https://glebbahmutov.com/blog/cypress-tips-and-tricks/#deal-with-type-module
