### ISSUE TITLE
Unable to get this to work

### ISSUE THREAD

**Issue by egucciar** [bahmutov/cypress-failed-log#5]
Hi,

I'm using Windows 7 and Cypres 1.1.3, and this is not working. Seemingly nothing is happening. I added package.json script, installed the dependencies, included it in the index.js file in cypress/support. but there's no telling that this ran or did not. it doesnt work.

**Comment by bahmutov** [comment]
Ohh, have not used this in a while - have you tried it on Linux and /or earlier versions of Cypress? Where did it break?

**Comment by egucciar** [comment]
@bahmutov 

i do not have linux readily available to me. However I changed up my configuration so now am able to get the Email from Jenkins, thus i do not need this library right now. Thanks!
